services:
  ml-service:
    build: 
      context: ./app/machine_learning
      dockerfile: Dockerfile
    container_name: ml-service
    ports:
      - "5001:5001"
    networks:
      - app-network
    volumes:
      - ./app/machine_learning/saved_models:/app/saved_models
      - ./app/data:/app/data

  web-app:
    build:
      context: ./app/flask_app
      dockerfile: Dockerfile
    container_name: web-app
    ports:
      - "5000:5000"
    depends_on:
      - ml-service
    environment:
      - ML_SERVICE_URL=http://ml-service:5001
    networks:
      - app-network

networks:
  app-network:
    driver: bridge